platform :ios, :deployment_target => '5.0'

xcodeproj 'HTKitDemo'

pod 'HTRasterView'
pod 'HTAutocompleteTextField'
pod 'HTGradientEasing'
pod 'HTDelegateProxy'
pod 'SFObservers'
pod 'UIViewPlusPosition'
pod 'HTCoreImage'
pod 'HTGraphics'
